---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 2048-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 2048-app
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: 2048-app
    spec:
      containers:
      - name: 2048-app
        # Replace with your docker registry info
        image: babywalkeracr.azurecr.io/tekton-demo/2048-app@sha256:e0edb5b67dda11f6a6880a9e8b2cfd4e60c62c65a1db7bf783986ee81174c400
        ports:
        - name: http
          containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        resources:
          limits:
            cpu: "0.1"
            memory: 100Mi
